<a href="https://colab.research.google.com/github/NotBizzaark/PyTorch/blob/main/Intro_To_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors


*   A torch. tensor is a multi-dimensional matrix containing elements of a single data type.
*   Similar to numpy arrays, but full of fun things that make them work better on GPU's(vs regular CPU's).
*   Default data type of float32.
*   More suitable for deep learning than a numpy array



In [3]:
import torch
import numpy as np

#Lists

In [4]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

#Numpy Arrays

In [5]:
np1 = np.random.rand(3, 4)
np1

array([[0.67901141, 0.30646326, 0.99102384, 0.65478766],
       [0.70807339, 0.60599288, 0.44739749, 0.88670531],
       [0.52057422, 0.25892119, 0.87110397, 0.15895456]])

In [6]:
np1.dtype

dtype('float64')

#TENSORS

In [7]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 0.7433, -1.3869, -1.9328,  0.1365],
        [ 0.1536, -0.2333, -1.1574, -1.2603],
        [ 0.1032, -0.3295, -1.1585, -0.7166]])

In [8]:
tensor_2d.dtype

torch.float32

In [9]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6790, 0.3065, 0.9910, 0.6548],
        [0.7081, 0.6060, 0.4474, 0.8867],
        [0.5206, 0.2589, 0.8711, 0.1590]], dtype=torch.float64)

## Reshape & Slicing

In [11]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# Reshape & view
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
# reshape if we don't know the number of items using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
my_torch2 = my_torch2.reshape(-1, 5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [24]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_torch4 = my_torch3.view(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
# Difference between view & reshape
# https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [28]:
# with view & reshape, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_torch6 = my_torch5.reshape(2, 5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [31]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [32]:
# Change will be reflected

In [33]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# Grab a specific item
my_torch7[7]

tensor(7)

In [35]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [36]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [37]:
# Return Column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

## Tensor Math Operations

In [38]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])


In [39]:
# addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [40]:
# additon longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [41]:
# subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [43]:
# Sub Function
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [44]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [45]:
# Multi Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [46]:
# Division
tensor_b/ tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [49]:
# Div Longhand
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [52]:
# Remainder Module
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [53]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [54]:
# Exponennt
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [56]:
#Exp Longhand
torch.pow(tensor_b, tensor_a)

tensor([   5,   36,  343, 4096])

In [57]:
# another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [58]:
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [60]:
tensor_a

tensor([ 6,  8, 10, 12])

In [61]:
torch.add_(tensor_a, tesnor_b)

AttributeError: module 'torch' has no attribute 'add_'